apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - name: myapp
        image: nginx
        volumeMounts:
        - name: myvolume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: my-nfs-claim