apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: w0rdpr355
