apiVersion: v1
data:
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_PASSWORD: dzByZHByMzU1
  MYSQL_ROOT_PASSWORD: bXlwYXNz
  MYSQL_USER: d29yZHByZXNz
kind: Secret
metadata:
  creationTimestamp: "2025-07-28T20:07:53Z"
  name: mysecret
  namespace: default
  resourceVersion: "117070"
  uid: 883acf8f-33be-466e-9d6d-47e63428d0dc
type: Opaque
