apiVersion: v1
kind: Pod
metadata:
  name: nfs-debug
spec:
  hostNetwork: true
  containers:
    - name: debug
      image: ubuntu
      command: [ "sleep", "infinity" ]
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
  restartPolicy: Never
