apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/k8s-share
    server: 10.0.0.4
#  mountOption:
#    - vers=4
#    - minorversion=1
#    - noac