apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  labels:
    app: mystatefulset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mystatefulset
  template:
    metadata:
      labels:
        app: mystatefulset
    spec:
      containers:
      - name: mystatefulset
        image: nginx
